#!/usr/bin/env bash

BACKUPDIR="/mnt/storage/backup/"


if [ -f /var/run/${UID}/backsync/in_progress ]; then
	echo "backsync is already running"
	exit 0
fi
if [ -d $BACKUPDIR ]; then
	touch /var/run/user/${UID}/backsync/in_progress
	rsync \
		-avhuP \
		$HOME \
		--delete --exclude-from=$HOME/.exclude \
		$BACKUPDIR
else
	echo "Target directory $BACKUPDIR does not exist"
fi
