#!/usr/bin/env bash

set -e

BACKUPDIR="alc@[2604:6000:1201:81:76d4:35ff:fea9:c5eb]:/mnt/storage/backup/"

if [ -f /tmp/everysync_in_progress ]; then
	echo "eversync is already running"
	exit 0
fi

if [ -d $HOME ]; then
	touch ~/.lock/subsys/everysync_in_progress
	rsync \
		-6ahuP \
		$HOME \
		--exclude-from=$HOME/.exclude.txt --delete \
		$BACKUPDIR
	/bin/rm -f ~/.lock/subsys/everysync_in_progress
else
	echo "Target directory $HOME does not exist"
fi
