#!/usr/bin/env bash

set -e

BACKUPDIR="alc@192.168.0.22:/mnt/storage/backup/"

if [ -f /var/run/user/${UID}/everysync/in_progress ]; then
	echo "eversync is already running"
	exit 0
fi

if [ -d $HOME ]; then
	touch /var/run/user/${UID}/everysync/in_progress
	rsync \
		-ahuP \
		$HOME \
		--exclude-from=$HOME/.exclude.txt --delete \
		$BACKUPDIR
else
	echo "Target directory $HOME does not exist"
fi
